### PR TITLE
added line to upstart config to write the statsd pid file using the d…

### PR DESCRIPTION
**Pull request by DocLabyrinth**
The cookbook supplies an attribute to configure where the pid file is written to, but unless I missed something it wasn't actually being used. This caused me problems when trying to get monit to monitor statsd. The change in this pull request solved the problem and the pid file is now generated as expected

### CODE REVIEW

**Comment by mheffner** [comment]
@DocLabyrinth Makes sense. Should the PID file be removed in a post-stop section?

**Comment by DocLabyrinth** [comment]
Post-stop section added by https://github.com/prioridata/statsd-cookbook/commit/382f8afdfd2de28d5de606c2bc10cadcb82593e7

**Comment by mheffner** [comment]
@DocLabyrinth Why the addition of the vsysinit bits? I think that should ideally be in a different PR.

**Comment by DocLabyrinth** [comment]
Ah sorry my mistake I forgot the vsysinit commit was also in there, i'll split it into two PRs

**Pull request closed without merging**
